version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - symfony:/var/www/demo:ro
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: php-fpm
    volumes:
      - symfony:/var/www/demo
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  symfony:
  db_data: