- name: Download composer
  ansible.builtin.get_url:
    url: https://getcomposer.org/download/2.7.1/composer.phar
    dest: /usr/local/bin/composer
    checksum: sha256:1ffd0be3f27e237b1ae47f9e8f29f96ac7f50a0bd9eef4f88cdbe94dd04bfff0
  become: yes

- name: Change permissions
  file:
    path: /usr/local/bin/composer
    mode: a+x
  become: yes
