name: Deploy
on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook locally
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          ansible-playbook ansible/playbook.yml -i ansible/inventory.yaml \
          --extra-vars "ansible_ssh_private_key_file=./private_key \
          ansible_host=$REMOTE_HOST ansible_user=$REMOTE_USER db_host=$DB_HOST \
          db_name=$DB_NAME db_user=$DB_USER db_password=$DB_PASSWORD" \
          --ssh-common-args='-o StrictHostKeyChecking=no'
          
          rm -f private_key